enum UserRole { ADMIN, STUDENT, DEALER, DELIVERY_BOY }
enum SubTier { BASIC, PRO, PLUS }
enum OfferType { SELL, LEND, RENT, SHARE, EXCHANGE }
enum TradeStatus { PENDING, ACCEPTED, REJECTED, COMPLETED, OVERDUE, CANCELLED, IN_PROGRESS }
enum ItemCondition { NEW, LIKE_NEW, GOOD, FAIR, POOR }
enum DeliveryStatus { ASSIGNED, PICKED_UP, IN_TRANSIT, DELIVERED, FAILED }
enum RentalUnit { DAY, WEEK, MONTH }
enum VisiScope {PUBLIC, COLLEGE, CLASS}
enum NotificType { TRADE_REQUEST, TRADE_ACCEPTED, TRADE_REJECTED, REMINDER, REVIEW, MESSAGE, SYSTEM }
enum RequestStatus { OPEN, MATCHED, FULFILLED, CLOSED, EXPIRED }
enum UrgentLevel { LOW, MEDIUM, HIGH, URGENT }
enum StuffType { BOOK, STATIONERY, ELECTRONICS, NOTES, OTHER }
enum ReviewType { UNIVERSAL_STUFF, THANK_YOU_MESSAGE, USER_RATING }
enum ReminderType { RETURN_DUE, PICKUP_DUE, OFFER_EXPIRY, PAYMENT_DUE, CUSTOM }
enum BookType { TEXTBOOK, REFERENCE, NOVEL, GUIDE, NOTES, OTHER }
enum StationeryType { WRITING, DRAWING, CALCULATION, STORAGE, OFFICE_SUPPLIES, OTHER }